### ISSUE TITLE
Migrate gem back to puppetlabs

### ISSUE THREAD

**Issue by ekohl** [puppetlabs/beaker-puppet#229]
This gem was migrated together with all other beaker gems. Back then it was used by Vox Pupuli, but now we've migrated to [beaker_puppet_helpers](https://github.com/voxpupuli/beaker_puppet_helpers) which is a really stripped down version of this gem.

beaker-puppet contains a lot of logic to test puppetserver and the only user of that is puppetlabs. That's why I'm proposing to migrate it back.

**Comment by bastelfreak** [comment]
I fully agree with @ekohl. it doesn't make sense for us to maintain. I consider it a legacy gem that's not used by beaker 5 anymore.

**Comment by bastelfreak** [comment]
There's also https://github.com/voxpupuli/beaker-module_install_helper that we don't use anymore. If Puppet still relies on it I suggest we migrate it to them as well.

**Comment by joshcooper** [comment]
I'd be fine migrating it back. I think we're the only ones making changes these days, like Amazon Linux 2023. @binford2k thoughts?

**Comment by bastelfreak** [comment]
Some of you have permissions to migrate repos away. If something isn't working out please let us know. And tell us the desired rubygems account email address so we can add it to the gem.
